apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: pipeline-prod-aiops-consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: CLICKHOUSE_HOST
          value: "clickhouse"